version: dev.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild -m GOLExtractor.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: Release
  name: GOLExtractor
deploy:
- provider: GitHub
  release: windows_development_build
  description: The most recent build - current version
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: ParadoxGameConverters/GOLExtractor
  artifact: GOLExtractor
  prerelease: true
  force_update: true
